---
title: How Authoritarian Party Institutionalization Influences the Effects of Corruption
---
<style type="text/css">

body, td {
   font-size: 16px;
}
code.r{
  font-size: 12px;
}
pre {
  font-size: 12px
}
</style>

<link rel="stylesheet" href="styles.css" type="text/css">

This book project is a work in progress based on my dissertation. 

In contrast to the rich literature that links corruption to government dissatisfaction in democratic countries, there is little empirical work that explores whether corruption breeds government discontent, manifested in anti-government protest in authoritarian regimes, with implications for understanding how autocracies endure. Indeed, while mass protests now outpace military coups as the most common way dictatorships fall in the 20th century, we have few explanations for understanding why corruption breeds protest in some autocracies while others appear relatively immune.

This book asks why corruption breeds anti-regime dissent in some autocracies but not others? I argue that institutionalized ruling parties mitigate the mobilization effect of corruption through three possible mechanisms. First, institutionalized parties may help regulate corruption, making every day corruption interactions with the government and its officials more predictable, such that people who have contact with the party are less likely to feel resentment from corruption. Institutionalized parties may also provide autocracies with a mechanism to extend the economic benefits of corruption to a large group of citizens who are connected to the party. Not only are the citizens who might benefit from the current regime less likely to join a protest, but common knowledge of these citizens’ stake in the corruption regime may deter others from mobilizing protest. Finally, autocratic party institutionalization may channel citizens' discontent with corruption into a state-sanctioned system for expressing grievance and thus reduce anti-regime mobilization.

Chapters in this book test the above theory cross-nationally, sub-nationally, and at individual level. 


