---
pagetitle: Research
---
<style type="text/css">

body, td {
   font-size: 16px;
}
code.r{
  font-size: 12px;
}
pre {
  font-size: 12px
}
</style>

<link rel="stylesheet" href="styles.css" type="text/css">

<font size='5'><b> Peer-reviewed Publications </b></font>

Park, Hyun Joon, Sara Chari Francisco, <b>M. Rosemary Pang</b>, Lulu Peng, and Guanqing Chi. 2023. ``Exposure to Anti-Black lives matter movement and obesity of the Black population.” *Social Science \& Medicine*, 316, 114265（Published online in 2021） [Link](https://doi.org/10.1016/j.socscimed.2021.114265)

Huang, Guan, and <b>M. Rosemary Pang</b>. 2022. ``How a non-democratic regime maintains its legitimacy over time: A study of changes in Chinese Communist Party legitimacy after 1949.''  *Asian Journal of Comparative Politics*, 7 (4), pp. 971-987 [Link](https://doi.org/10.1177/20578911221078030)

Ma, Deyong, and <b>M. Rosemary Pang</b>. 2017. ``The Rise and Fall of Electoral Democracy: A Social Evolutionary Approach to Direct Election Experiments in Local China.” *Journal of Chinese Political Science*, 22 (4), pp. 601-624 [Link](https://link.springer.com/article/10.1007/s11366-017-9510-y)

<font size='5'><b> Editor-reviewed Publications </b></font>

<b>M. Rosemary Pang</b>. 2017. ``Book Review. Bruce J. Dickson, The Dictator’s Dilemma: The Chinese Communist Party’s Strategy for Survival.” *Journal of Asian Politics and History*. Fall 2017, No. 10

<font size='5'><b> Working Papers </b></font>

``How Ruling Party Institutionalization Influences Corruption’s Effects on Protests?” (Under review)

``Subnational Ruling Party Institutionalization and its Mitigation Effects on Corruption: A Case Study of China"

``A Subnational Measure of Corruption in China Using News Report"

``How anti-corruption campaigns influence citizens’ perception of corruption" (with Dong Erico Yu and Yuehong Cassandra Tai)

``International Mudslinging in Vain: An Experiment of COVID- Related Propaganda and Overseas Nationals’ Support for Autocratic Government.” (with Jia Li)

``Unhappy Voters and Where to Find Them: An Analysis of Chinese University Students’ Understanding of Democracy and Voting Behavior.”

<font size='5'><b> Work in Progress </b></font>
``The Association Between County-Level Racism
Towards Asians During COVID-19 Pandemic and Asian’s Health Outcomes." (with Hyun Joon Park and Sara Chari Francisco)

``Towards Personalistic Rule: Evidence from Textbooks in China." (with Dong Erico Yu and Yuehong Cassandra Tai)

<font size='5'><b> Online Contributions </b></font>

* In Chinese
   + [世界价值观调查的跨国可比性讨论](https://chuansongme.com/n/1509213751415) ``A discussion on whether World Value Survey data is comparable cross-country"
   + [多层次贝叶斯模型在跨国时间序列分析中的应用](https://chuansongme.com/n/1513400251021) ``The application of multi-level Bayes models using cross-sectional time series data"
   + [当我们测量腐败时，我们在测量什么?](https://mp.weixin.qq.com/s/EqYG9cRK2nM5xGgRawIKYQ) ``What are we actually measuring when we measure corruption?"
   + [社会科学中使用网络数据的挑战和解决办法](https://mp.weixin.qq.com/s/siD_viqcx_5uRfIO5oQjBw) ``The challenges and solutions of using online data in social science"
